vich_uploader:
    db_driver: orm

    mappings:
        slider_image:
            uri_prefix: /images/slider
            upload_destination: '%kernel.project_dir%/public/images/slider'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        news_image:
            uri_prefix: /images/news
            upload_destination: '%kernel.project_dir%/public/images/news'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
